<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>PS5 PKG Tool</AssemblyName>
    <RootNamespace>PS5PKGTool</RootNamespace>
    <Product>PS5 PKG Tool</Product>
    <Company>pearlxcore</Company>
    <Copyright>Copyright © pearlxcore</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PS5PKGTool.Core\PS5PKGTool.Core.csproj" />
    <ProjectReference Include="..\PS5PKGTool.Ffpfsc\PS5PKGTool.Ffpfsc.csproj" />
    <ProjectReference Include="..\PS5PKGTool.Ufs2\PS5PKGTool.Ufs2.csproj" />
    <ProjectReference Include="..\..\DarkUI\DarkUI\DarkUI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ThirdParty\Oodle\oo2core_9_win64.dll">
      <Link>oo2core_9_win64.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
